# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-09-04 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('nasa:pds', 'NASA'), ('esa:psa', 'ESA'), ('jaxa:darts', 'JAXA')], default='NASA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateNameFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateNameLast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_password', models.CharField(max_length=256)),
                ('new_password', models.CharField(max_length=256)),
                ('confirm_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('nasa:pds', 'NASA'), ('esa:psa', 'ESA'), ('jaxa:darts', 'JAXA')], default='NASA', max_length=10)),
                ('directory', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
