# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-01-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.CharField(default='NASA', max_length=10),
        ),
    ]
