# Generated by Django 4.2 on 2024-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20240111_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.CharField(choices=[('nasa:pds', 'NASA'), ('esa:psa', 'ESA'), ('jaxa:darts', 'JAXA')], default='NASA', max_length=10),
        ),
    ]
