# Generated by Django 4.2 on 2026-08-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_userprofile_otp_code_userprofile_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
