# Generated by Django 4.2 on 2026-09-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateagency',
            name='agency',
            field=models.CharField(choices=[('nasa:pds', 'NASA'), ('esa:psa', 'ESA'), ('jaxa:darts', 'JAXA')], default='nasa:pds', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agency',
            field=models.CharField(choices=[('nasa:pds', 'NASA'), ('esa:psa', 'ESA'), ('jaxa:darts', 'JAXA')], default='nasa:pds', max_length=10),
        ),
    ]
