# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-09-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=500, unique=True)),
                ('answer', models.CharField(default='', max_length=500)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Joke',
                'verbose_name_plural': 'Jokes',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=main.models.get_user_document_directory)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
