# Generated by Django 4.2 on 2025-11-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
