# Generated by Django 4.2 on 2026-09-25 06:49

from django.db import migrations, models


def backfill_titles(apps, schema_editor):
    """Existing threads get their first question as a title, so the new chat
    list shows something readable instead of a column of "Untitled"."""
    Conversation = apps.get_model('assistant', 'Conversation')
    Message = apps.get_model('assistant', 'Message')
    for conv in Conversation.objects.filter(title=''):
        first = (Message.objects.filter(conversation=conv, role='user')
                 .order_by('created_at').values_list('text', flat=True).first())
        if not first:
            continue
        text = ' '.join(first.split())
        if len(text) > 50:
            text = text[:50].rsplit(' ', 1)[0] + '\u2026'
        # update() so the backfill does not bump updated_at and reorder the list
        Conversation.objects.filter(pk=conv.pk).update(title=text, title_source='question')


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_source',
            field=models.CharField(blank=True, choices=[('', 'Untitled'), ('question', 'First question'), ('ai', 'AI generated'), ('user', 'Renamed by user')], default='', max_length=8),
        ),
        migrations.RunPython(backfill_titles, migrations.RunPython.noop),
    ]
