# Generated by Django 4.2 on 2026-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='knowledge_used',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='message',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rating_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='rating_reason',
            field=models.CharField(blank=True, choices=[('', 'Not given'), ('wrong', 'Wrong information'), ('unanswered', "Didn't answer my question"), ('outdated', 'Out of date'), ('other', 'Other')], default='', max_length=12),
        ),
    ]
